version: '3.8'

services:
  market-gateway-service-1:
    build:
      context: .
      dockerfile: MarketGatewayService/Dockerfile
    depends_on:
      - redis

  market-gateway-service-2:
    build:
      context: .
      dockerfile: MarketGatewayService/Dockerfile
    depends_on:
      - redis

  price-update-handler-service:
    build:
      context: .
      dockerfile: PriceUpdateHandlerService/Dockerfile
    depends_on:
      - redis

  redis:
    image: "redis:latest"

  nginx:
    image: nginx:latest
    ports:
      - "15151:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - market-gateway-service-1
      - market-gateway-service-2